services:
  - type: web
    name: sistema-de-vendas
    env: python
    plan: free
    buildCommand: |
      cd ../frontend && npm install && npm run build
      cd ../backend
    startCommand: gunicorn src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    buildFilter:
      paths:
        - ../frontend/
        - ./
    autoDeploy: true
    rootDir: .
